[package]
name = "new_rgb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.4" }
dioxus-desktop = { version = "0.4" }

image = "0.23.12"
fltk = "^0.15.3"